import * as stylex from "@stylexjs/stylex";

const narrow = "@media (max-width: 56rem)";

const styles = stylex.create({
  page: {
    maxWidth: "76rem",
    marginInlineStart: "auto",
    marginInlineEnd: "auto",
    paddingTop: "clamp(2rem, 6vw, 4rem)",
    paddingRight: "clamp(1.25rem, 4vw, 3rem)",
    paddingBottom: "clamp(2rem, 6vw, 4rem)",
    paddingLeft: "clamp(1.25rem, 4vw, 3rem)",
  },
  eyebrow: { color: "var(--muted)", fontSize: "0.8rem", marginTop: 0, marginRight: 0, marginBottom: "1.25rem", marginLeft: 0 },
  title: {
    fontSize: "clamp(2.4rem, 5vw, 3.6rem)", fontWeight: 500, letterSpacing: "-0.03em",
    lineHeight: 1.05, marginTop: 0, marginRight: 0, marginBottom: "1rem", marginLeft: 0, textWrap: "balance",
  },
  lede: { color: "var(--muted)", fontSize: "1.1rem", lineHeight: 1.6, maxWidth: "64ch", marginTop: 0, marginRight: 0, marginBottom: "0.5rem", marginLeft: 0 },
  ledeEs: { color: "var(--muted)", fontSize: "0.95rem", lineHeight: 1.55, maxWidth: "64ch", marginTop: 0, marginRight: 0, marginBottom: "1.25rem", marginLeft: 0 },
  meta: { color: "var(--muted)", fontSize: "0.82rem", marginTop: 0, marginRight: 0, marginBottom: 0, marginLeft: 0 },
  disclaimer: {
    borderInlineStartColor: "var(--code-warning, #b45309)", borderInlineStartStyle: "solid", borderInlineStartWidth: "3px",
    color: "var(--muted)", fontSize: "0.92rem", lineHeight: 1.55,
    marginTop: "1.75rem", marginRight: 0, marginBottom: 0, marginLeft: 0,
    paddingTop: "0.65rem", paddingRight: "1rem", paddingBottom: "0.65rem", paddingLeft: "1rem",
  },
  metrics: {
    display: "grid", gridTemplateColumns: { default: "repeat(4, minmax(0, 1fr))", [narrow]: "repeat(2, minmax(0, 1fr))" },
    gap: "0.75rem", marginTop: "2.25rem", marginRight: 0, marginBottom: 0, marginLeft: 0,
    listStyleType: "none", listStyleImage: "none", listStylePosition: "outside", paddingTop: 0, paddingRight: 0, paddingBottom: 0, paddingLeft: 0,
  },
  metric: {
    backgroundColor: "var(--surface)", borderTopColor: "var(--rule)", borderRightColor: "var(--rule)",
    borderBottomColor: "var(--rule)", borderLeftColor: "var(--rule)",
    borderTopStyle: "solid", borderRightStyle: "solid", borderBottomStyle: "solid", borderLeftStyle: "solid",
    borderTopWidth: "1px", borderRightWidth: "1px", borderBottomWidth: "1px", borderLeftWidth: "1px",
    borderTopLeftRadius: "0.75rem", borderTopRightRadius: "0.75rem", borderBottomLeftRadius: "0.75rem", borderBottomRightRadius: "0.75rem",
    paddingTop: "1rem", paddingRight: "1.1rem", paddingBottom: "1rem", paddingLeft: "1.1rem",
  },
  metricValue: { display: "block", fontSize: "clamp(1.5rem, 3vw, 2.1rem)", fontWeight: 600, letterSpacing: "-0.02em", lineHeight: 1.1 },
  metricLabel: { color: "var(--muted)", display: "block", fontSize: "0.8rem", marginTop: "0.35rem" },
  brief: {
    backgroundColor: "var(--surface)", borderTopColor: "var(--rule)", borderRightColor: "var(--rule)",
    borderBottomColor: "var(--rule)", borderLeftColor: "var(--rule)",
    borderTopStyle: "solid", borderRightStyle: "solid", borderBottomStyle: "solid", borderLeftStyle: "solid",
    borderTopWidth: "1px", borderRightWidth: "1px", borderBottomWidth: "1px", borderLeftWidth: "1px",
    borderTopLeftRadius: "0.75rem", borderTopRightRadius: "0.75rem", borderBottomLeftRadius: "0.75rem", borderBottomRightRadius: "0.75rem",
    marginTop: "1.75rem", marginRight: 0, marginBottom: 0, marginLeft: 0,
    paddingTop: "1.1rem", paddingRight: "1.25rem", paddingBottom: "1.1rem", paddingLeft: "1.25rem",
  },
  briefLabel: { color: "var(--muted)", fontSize: "0.75rem", fontWeight: 600, letterSpacing: "0.06em", marginTop: 0, marginRight: 0, marginBottom: "0.5rem", marginLeft: 0, textTransform: "uppercase" },
  briefText: { fontSize: "1rem", lineHeight: 1.6, marginTop: 0, marginRight: 0, marginBottom: "0.5rem", marginLeft: 0 },
  briefTextEs: { color: "var(--muted)", fontSize: "0.92rem", lineHeight: 1.55, marginTop: 0, marginRight: 0, marginBottom: 0, marginLeft: 0 },
  filters: { marginTop: "2.5rem", marginRight: 0, marginBottom: 0, marginLeft: 0 },
  filterGroup: { borderTopWidth: 0, borderRightWidth: 0, borderBottomWidth: 0, borderLeftWidth: 0, marginTop: "0.9rem", marginRight: 0, marginBottom: 0, marginLeft: 0, paddingTop: 0, paddingRight: 0, paddingBottom: 0, paddingLeft: 0 },
  filterLegend: { color: "var(--muted)", fontSize: "0.78rem", fontWeight: 600, letterSpacing: "0.05em", marginBottom: "0.45rem", textTransform: "uppercase" },
  chips: { display: "flex", flexWrap: "wrap", gap: "0.4rem" },
  chip: {
    backgroundColor: { default: "transparent", ':is([aria-pressed="true"])': "var(--foreground)" },
    borderTopColor: "var(--rule)", borderRightColor: "var(--rule)", borderBottomColor: "var(--rule)", borderLeftColor: "var(--rule)",
    borderTopStyle: "solid", borderRightStyle: "solid", borderBottomStyle: "solid", borderLeftStyle: "solid",
    borderTopWidth: "1px", borderRightWidth: "1px", borderBottomWidth: "1px", borderLeftWidth: "1px",
    borderTopLeftRadius: "2rem", borderTopRightRadius: "2rem", borderBottomLeftRadius: "2rem", borderBottomRightRadius: "2rem",
    color: { default: "var(--muted)", ':is([aria-pressed="true"])': "var(--background)" },
    cursor: "pointer", fontFamily: "inherit", fontSize: "0.8rem", fontWeight: 500,
    paddingTop: "0.32rem", paddingRight: "0.75rem", paddingBottom: "0.32rem", paddingLeft: "0.75rem",
  },
  searchInput: {
    backgroundColor: "var(--surface)", borderTopColor: "var(--rule)", borderRightColor: "var(--rule)",
    borderBottomColor: "var(--rule)", borderLeftColor: "var(--rule)",
    borderTopStyle: "solid", borderRightStyle: "solid", borderBottomStyle: "solid", borderLeftStyle: "solid",
    borderTopWidth: "1px", borderRightWidth: "1px", borderBottomWidth: "1px", borderLeftWidth: "1px",
    borderTopLeftRadius: "0.5rem", borderTopRightRadius: "0.5rem", borderBottomLeftRadius: "0.5rem", borderBottomRightRadius: "0.5rem",
    color: "var(--foreground)", fontFamily: "inherit", fontSize: "0.95rem",
    marginTop: "0.9rem", maxWidth: "26rem",
    paddingTop: "0.6rem", paddingRight: "0.8rem", paddingBottom: "0.6rem", paddingLeft: "0.8rem", width: "100%",
  },
  filterStatus: { color: "var(--muted)", fontSize: "0.82rem", marginTop: "0.8rem", marginRight: 0, marginBottom: 0, marginLeft: 0 },
  section: {
    borderTopColor: "var(--rule)", borderTopStyle: "solid", borderTopWidth: "1px",
    marginTop: "2.75rem", paddingTop: "2.25rem",
  },
  sectionHeading: { fontSize: "1.35rem", fontWeight: 600, letterSpacing: "-0.01em", marginTop: 0, marginRight: 0, marginBottom: "0.35rem", marginLeft: 0 },
  sectionNote: { color: "var(--muted)", fontSize: "0.85rem", marginTop: 0, marginRight: 0, marginBottom: "1.5rem", marginLeft: 0 },
  signalList: { display: "grid", gap: "0.65rem", marginTop: 0, marginRight: 0, marginBottom: 0, marginLeft: 0, paddingTop: 0, paddingRight: 0, paddingBottom: 0, paddingLeft: 0 },
  signal: {
    backgroundColor: "var(--surface)", borderTopColor: "var(--rule)", borderRightColor: "var(--rule)",
    borderBottomColor: "var(--rule)", borderLeftColor: "var(--rule)",
    borderTopStyle: "solid", borderRightStyle: "solid", borderBottomStyle: "solid", borderLeftStyle: "solid",
    borderTopWidth: "1px", borderRightWidth: "1px", borderBottomWidth: "1px", borderLeftWidth: "1px",
    borderTopLeftRadius: "0.7rem", borderTopRightRadius: "0.7rem", borderBottomLeftRadius: "0.7rem", borderBottomRightRadius: "0.7rem",
    paddingTop: "0.95rem", paddingRight: "1.1rem", paddingBottom: "0.95rem", paddingLeft: "1.1rem",
  },
  signalTop: { alignItems: "baseline", display: "flex", flexWrap: "wrap", gap: "0.5rem", marginBottom: "0.35rem" },
  signalTitle: { fontSize: "0.98rem", fontWeight: 600, lineHeight: 1.35, marginTop: 0, marginRight: 0, marginBottom: 0, marginLeft: 0 },
  signalSummary: { color: "var(--muted)", fontSize: "0.88rem", lineHeight: 1.5, marginTop: "0.4rem", marginRight: 0, marginBottom: 0, marginLeft: 0 },
  signalMeta: { alignItems: "center", color: "var(--muted)", display: "flex", flexWrap: "wrap", fontSize: "0.76rem", gap: "0.4rem" },
  badge: {
    borderTopLeftRadius: "0.3rem", borderTopRightRadius: "0.3rem", borderBottomLeftRadius: "0.3rem", borderBottomRightRadius: "0.3rem",
    fontSize: "0.7rem", fontWeight: 700, letterSpacing: "0.05em", lineHeight: 1,
    paddingTop: "0.24rem", paddingRight: "0.45rem", paddingBottom: "0.24rem", paddingLeft: "0.45rem", textTransform: "uppercase",
  },
  badgeEmergency: { backgroundColor: "#7f1d1d", color: "#fecaca" },
  badgeWarning: { backgroundColor: "#7c2d12", color: "#fed7aa" },
  badgeWatch: { backgroundColor: "#713f12", color: "#fde68a" },
  badgeAdvisory: { backgroundColor: "#1e3a5f", color: "#bfdbfe" },
  badgeInfo: { backgroundColor: "color-mix(in srgb, var(--foreground) 8%, transparent)", color: "var(--muted)" },
  regionChip: {
    backgroundColor: "color-mix(in srgb, var(--foreground) 6%, transparent)",
    borderTopLeftRadius: "0.3rem", borderTopRightRadius: "0.3rem", borderBottomLeftRadius: "0.3rem", borderBottomRightRadius: "0.3rem",
    fontSize: "0.72rem", paddingTop: "0.2rem", paddingRight: "0.45rem", paddingBottom: "0.2rem", paddingLeft: "0.45rem",
  },
  sourceLink: { color: "var(--link)", textDecorationThickness: "1px", textUnderlineOffset: "0.16em" },
  healthTable: { borderCollapse: "collapse", fontSize: "0.85rem", width: "100%" },
  healthCell: {
    borderBottomColor: "var(--rule)", borderBottomStyle: "solid", borderBottomWidth: "1px",
    paddingTop: "0.55rem", paddingRight: "0.75rem", paddingBottom: "0.55rem", paddingLeft: "0.5rem", textAlign: "start", verticalAlign: "top",
  },
  healthHead: { color: "var(--muted)", fontSize: "0.75rem", fontWeight: 600, letterSpacing: "0.04em", textTransform: "uppercase" },
  statusOk: { color: "#15803d" },
  statusFail: { color: "#b91c1c" },
  resourceGroups: { display: "grid", gap: "1.75rem", gridTemplateColumns: { default: "repeat(3, minmax(0, 1fr))", [narrow]: "1fr" } },
  resourceGroup: { marginTop: 0, marginRight: 0, marginBottom: 0, marginLeft: 0 },
  resourceHeading: { fontSize: "0.95rem", fontWeight: 600, marginTop: 0, marginRight: 0, marginBottom: "0.6rem", marginLeft: 0 },
  resourceList: { display: "grid", gap: "0.5rem", marginTop: 0, marginRight: 0, marginBottom: 0, marginLeft: 0, paddingTop: 0, paddingRight: 0, paddingBottom: 0, paddingLeft: 0 },
  resourceItem: { fontSize: "0.86rem", lineHeight: 1.45, listStyleType: "none", listStyleImage: "none", listStylePosition: "outside" },
  resourceNote: { color: "var(--muted)", display: "block", fontSize: "0.78rem" },
  sparkline: { display: "block", height: "auto", marginTop: "1rem", maxWidth: "44rem", width: "100%" },
  methodology: { color: "var(--muted)", fontSize: "0.85rem", lineHeight: 1.6, maxWidth: "68ch" },
});

export type PrSlot = keyof typeof styles;

export function prClasses(...slots: readonly PrSlot[]): string {
  return stylex.props(...slots.map((slot) => styles[slot])).className ?? "";
}
