import * as stylex from "@stylexjs/stylex";

const reducedMotion = "@media (prefers-reduced-motion: reduce)";
const hoverCapable = "@media (hover: hover)";

const attentionPulse = stylex.keyframes({
  "0%": { boxShadow: "0 0 0 1px var(--color-attention)" },
  "50%": {
    boxShadow: "0 0 0 3px color-mix(in oklab, var(--color-attention) 45%, transparent)",
  },
  "100%": { boxShadow: "0 0 0 1px var(--color-attention)" },
});

export const sessionCardStyles = stylex.create({
  attention: {
    animationComposition: { default: "replace", [reducedMotion]: "replace" },
    animationDelay: { default: "0s", [reducedMotion]: "0s" },
    animationDirection: { default: "normal", [reducedMotion]: "normal" },
    animationDuration: {
      default: "2.4s",
      [reducedMotion]: "0s",
    },
    animationFillMode: { default: "none", [reducedMotion]: "none" },
    animationIterationCount: {
      default: "infinite",
      [reducedMotion]: 1,
    },
    animationName: {
      default: attentionPulse,
      [reducedMotion]: "none",
    },
    animationPlayState: { default: "running", [reducedMotion]: "running" },
    animationRangeEnd: { default: "normal", [reducedMotion]: "normal" },
    animationRangeStart: { default: "normal", [reducedMotion]: "normal" },
    animationTimeline: { default: "auto", [reducedMotion]: "auto" },
    animationTimingFunction: {
      default: "ease-in-out",
      [reducedMotion]: "ease",
    },
    borderBottomColor: "var(--color-attention)",
    borderLeftColor: "var(--color-attention)",
    borderRightColor: "var(--color-attention)",
    borderTopColor: "var(--color-attention)",
  },
  card: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    overflow: "hidden",
  },
  choice: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "currentColor",
    borderRadius: "0.375rem",
    borderStyle: "solid",
    borderWidth: "1px",
    display: "flex",
    fontSize: "0.875rem",
    width: "100%",
    justifyContent: "space-between",
    lineHeight: "1.25rem",
    minHeight: "2.75rem",
    paddingBottom: 0,
    paddingLeft: "0.75rem",
    paddingRight: "0.75rem",
    paddingTop: 0,
    textAlign: "start",
    ":disabled": { cursor: "not-allowed", opacity: 0.5 },
  },
  choiceIdle: {
    borderColor: "var(--color-line)",
    color: "var(--color-ink)",
  },
  choiceSelected: {
    borderColor: "var(--color-accent)",
    color: "var(--color-accent)",
  },
  composer: {
    borderTopColor: "var(--color-line)",
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    display: "flex",
    flexDirection: "column",
    gap: "0.375rem",
    paddingBottom: "0.5rem",
    paddingLeft: "0.5rem",
    paddingRight: "0.5rem",
    paddingTop: "0.5rem",
  },
  composerIcon: {
    minHeight: "2.25rem",
    minWidth: "2.25rem",
  },
  danger: {
    color: "var(--color-danger)",
    fontSize: "0.75rem",
    lineHeight: "1rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "normal",
  },
  dialogInput: { marginTop: "0.75rem" },
  dialogValue: {
    fontFamily: "var(--font-mono)",
    fontSize: "0.75rem",
    lineHeight: "1rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: "0.75rem",
    overflowWrap: "normal",
    userSelect: "all",
    wordBreak: "break-all",
  },
  dragActive: {
    outlineColor: "var(--focus)",
    outlineOffset: "2px",
    outlineStyle: "solid",
    outlineWidth: "2px",
  },
  dragHandle: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "currentColor",
    borderRadius: "0.25rem",
    borderStyle: "solid",
    borderWidth: 0,
    color: "var(--color-ink-muted)",
    cursor: "grab",
    display: "flex",
    flexShrink: 0,
    justifyContent: "center",
    minHeight: "2rem",
    minWidth: "1.5rem",
    padding: 0,
    touchAction: "none",
    ":hover": {
      color: { default: null, [hoverCapable]: "var(--color-ink)" },
    },
  },
  dragging: { opacity: 0.6 },
  dropTarget: {
    borderBottomColor: "var(--color-accent)",
    borderLeftColor: "var(--color-accent)",
    borderRightColor: "var(--color-accent)",
    borderTopColor: "var(--color-accent)",
  },
  fileInput: { display: "none" },
  form: {
    alignItems: "flex-end",
    borderRadius: "0.375rem",
    display: "flex",
    gap: "0.25rem",
  },
  header: {
    alignItems: "center",
    display: "flex",
    gap: "0.25rem",
    minHeight: "2rem",
    paddingBottom: "0.25rem",
    paddingLeft: "0.25rem",
    paddingRight: "0.25rem",
    paddingTop: "0.25rem",
  },
  heading: {
    fontFamily: "var(--font-sans)",
    fontSize: "1rem",
    fontWeight: 600,
    lineHeight: "1.5rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "normal",
  },
  headingSpaced: { marginTop: "1rem" },
  menu: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
  },
  menuDescription: {
    color: "var(--color-ink-muted)",
    fontSize: "0.75rem",
    lineHeight: "1rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: "0.25rem",
    overflowWrap: "normal",
  },
  menuOptions: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    marginTop: "0.5rem",
  },
  notice: {
    color: "var(--color-ink-muted)",
    fontSize: "0.75rem",
    lineHeight: "1rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "normal",
  },
  quiet: {
    color: "var(--color-ink-muted)",
    fontSize: "0.75rem",
    lineHeight: "1rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "normal",
    paddingLeft: "0.5rem",
    paddingRight: "0.5rem",
  },
  status: { marginTop: "0.5rem" },
  title: {
    fontFamily: "var(--font-sans)",
    fontSize: "0.8125rem",
    fontWeight: 600,
    lineHeight: "1.125rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflow: "hidden",
    overflowWrap: "normal",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  titleBlock: {
    alignItems: "center",
    display: "flex",
    flex: 1,
    gap: "0.5rem",
    minWidth: 0,
  },
});
