import * as stylex from "@stylexjs/stylex";

const gridBreakpoint = "@media (min-width: 40rem)";

export const gridScreenStyles = stylex.create({
  cardGrid: {
    alignItems: "start",
    display: "grid",
    gap: "0.75rem",
    gridTemplateColumns: {
      default: "minmax(0, 1fr)",
      [gridBreakpoint]: "repeat(auto-fill, minmax(22rem, 1fr))",
    },
  },
  controls: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: "0.5rem",
  },
  danger: {
    color: "var(--color-danger)",
    fontSize: "0.75rem",
    lineHeight: "1rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "normal",
  },
  fileInput: { display: "none" },
  form: {
    alignItems: "flex-end",
    display: "flex",
    flex: 1,
    gap: "0.5rem",
  },
  header: {
    backgroundColor: "var(--color-surface)",
    borderBottomColor: "var(--color-line)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    paddingBottom: "0.75rem",
    paddingLeft: "max(1rem, env(safe-area-inset-left))",
    paddingRight: "max(1rem, env(safe-area-inset-right))",
    paddingTop: "calc(0.75rem + env(safe-area-inset-top))",
    position: "sticky",
    top: 0,
    zIndex: 20,
  },
  headerRow: {
    alignItems: "flex-end",
    display: "flex",
    gap: "0.5rem",
  },
  label: {
    alignItems: "center",
    color: "var(--color-ink-muted)",
    display: "flex",
    fontSize: "0.75rem",
    gap: "0.25rem",
    lineHeight: "1rem",
  },
  loadMore: {
    display: "flex",
    justifyContent: "center",
    marginTop: "1rem",
  },
  main: {
    flex: 1,
    paddingBottom: "calc(1rem + env(safe-area-inset-bottom))",
    paddingLeft: "max(1rem, env(safe-area-inset-left))",
    paddingRight: "max(1rem, env(safe-area-inset-right))",
    paddingTop: "1rem",
  },
  quiet: {
    color: "var(--color-ink-muted)",
    fontSize: "0.75rem",
    lineHeight: "1rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "normal",
  },
  quietBody: {
    color: "var(--color-ink-muted)",
    fontSize: "0.875rem",
    lineHeight: "1.25rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    overflowWrap: "normal",
  },
  root: {
    display: "flex",
    flexDirection: "column",
    marginLeft: "auto",
    marginRight: "auto",
    maxWidth: "72rem",
    minHeight: "100dvh",
    width: "100%",
  },
  select: {
    backgroundColor: "var(--color-surface-input)",
    borderColor: "var(--color-control)",
    borderRadius: "0.375rem",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--color-ink)",
    fontSize: "0.8125rem",
    lineHeight: "1.125rem",
    minHeight: "2rem",
    paddingBottom: 0,
    paddingLeft: "0.5rem",
    paddingRight: "0.5rem",
    paddingTop: 0,
  },
});
